In [1]:
import pandas as pd
import collections

In [2]:
df = pd.read_csv('data_csv.csv')

In [3]:
df

                         Name Code
0                     Ecuador   EC
1                  Bangladesh   BD
2                  Madagascar   MG
3                 Saint Lucia   LC
4                       Spain   ES
..                        ...  ...
244                    Guinea   GN
245               El Salvador   SV
246                   Germany   DE
247  Turks and Caicos Islands   TC
248                 Lithuania   LT

[249 rows x 2 columns]

In [4]:
df['Name'] = df['Name'].astype(str)

In [5]:
df['Code'] = df['Code'].astype(str)

In [6]:
df

                         Name Code
0                     Ecuador   EC
1                  Bangladesh   BD
2                  Madagascar   MG
3                 Saint Lucia   LC
4                       Spain   ES
..                        ...  ...
244                    Guinea   GN
245               El Salvador   SV
246                   Germany   DE
247  Turks and Caicos Islands   TC
248                 Lithuania   LT

[249 rows x 2 columns]

### Converting into Dictionary

In [7]:
dictt = df.set_index('Code')['Name'].to_dict()

### Ordered Dict AT keys

In [8]:
od = collections.OrderedDict(sorted(dictt.items()))

In [9]:
od

OrderedDict([('AD', 'Andorra'),
             ('AE', 'United Arab Emirates'),
             ('AF', 'Afghanistan'),
             ('AG', 'Antigua and Barbuda'),
             ('AI', 'Anguilla'),
             ('AL', 'Albania'),
             ('AM', 'Armenia'),
             ('AO', 'Angola'),
             ('AQ', 'Antarctica'),
             ('AR', 'Argentina'),
             ('AS', 'American Samoa'),
             ('AT', 'Austria'),
             ('AU', 'Australia'),
             ('AW', 'Aruba'),
             ('AX', 'Åland Islands'),
             ('AZ', 'Azerbaijan'),
             ('BA', 'Bosnia and Herzegovina'),
             ('BB', 'Barbados'),
             ('BD', 'Bangladesh'),
             ('BE', 'Belgium'),
             ('BF', 'Burkina Faso'),
             ('BG', 'Bulgaria'),
             ('BH', 'Bahrain'),
             ('BI', 'Burundi'),
             ('BJ', 'Benin'),
             ('BL', 'Saint Barthélemy'),
             ('BM', 'Bermuda'),
             ('BN', 'Brunei Darussalam'),
             ('BO', 'Bolivia, Plurinational State of'),
             ('BQ', 'Bonaire, Sint Eustatius and Saba'),
             ('BR', 'Brazil'),
             ('BS', 'Bahamas'),
             ('BT', 'Bhutan'),
             ('BV', 'Bouvet Island'),
             ('BW', 'Botswana'),
             ('BY', 'Belarus'),
             ('BZ', 'Belize'),
             ('CA', 'Canada'),
             ('CC', 'Cocos (Keeling) Islands'),
             ('CD', 'Congo, the Democratic Republic of the'),
             ('CF', 'Central African Republic'),
             ('CG', 'Congo'),
             ('CH', 'Switzerland'),
             ('CI', "Côte d'Ivoire"),
             ('CK', 'Cook Islands'),
             ('CL', 'Chile'),
             ('CM', 'Cameroon'),
             ('CN', 'China'),
             ('CO', 'Colombia'),
             ('CR', 'Costa Rica'),
             ('CU', 'Cuba'),
             ('CV', 'Cape Verde'),
             ('CW', 'Curaçao'),
             ('CX', 'Christmas Island'),
             ('CY', 'Cyprus'),
             ('CZ', 'Czech Republic'),
             ('DE', 'Germany'),
             ('DJ', 'Djibouti'),
             ('DK', 'Denmark'),
             ('DM', 'Dominica'),
             ('DO', 'Dominican Republic'),
             ('DZ', 'Algeria'),
             ('EC', 'Ecuador'),
             ('EE', 'Estonia'),
             ('EG', 'Egypt'),
             ('EH', 'Western Sahara'),
             ('ER', 'Eritrea'),
             ('ES', 'Spain'),
             ('ET', 'Ethiopia'),
             ('FI', 'Finland'),
             ('FJ', 'Fiji'),
             ('FK', 'Falkland Islands (Malvinas)'),
             ('FM', 'Micronesia, Federated States of'),
             ('FO', 'Faroe Islands'),
             ('FR', 'France'),
             ('GA', 'Gabon'),
             ('GB', 'United Kingdom'),
             ('GD', 'Grenada'),
             ('GE', 'Georgia'),
             ('GF', 'French Guiana'),
             ('GG', 'Guernsey'),
             ('GH', 'Ghana'),
             ('GI', 'Gibraltar'),
             ('GL', 'Greenland'),
             ('GM', 'Gambia'),
             ('GN', 'Guinea'),
             ('GP', 'Guadeloupe'),
             ('GQ', 'Equatorial Guinea'),
             ('GR', 'Greece'),
             ('GS', 'South Georgia and the South Sandwich Islands'),
             ('GT', 'Guatemala'),
             ('GU', 'Guam'),
             ('GW', 'Guinea-Bissau'),
             ('GY', 'Guyana'),
             ('HK', 'Hong Kong'),
             ('HM', 'Heard Island and McDonald Islands'),
             ('HN', 'Honduras'),
             ('HR', 'Croatia'),
             ('HT', 'Haiti'),
             ('HU', 'Hungary'),
             ('ID', 'Indonesia'),
             ('IE', 'Ireland'),
             ('IL', 'Israel'),
             ('IM', 'Isle of Man'),
             ('IN', 'India'),
             ('IO', 'British Indian Ocean Territory'),
             ('IQ', 'Iraq'),
             ('IR', 'Iran, Islamic Republic of'),
             ('IS', 'Iceland'),
             ('IT', 'Italy'),
             ('JE', 'Jersey'),
             ('JM', 'Jamaica'),
             ('JO', 'Jordan'),
             ('JP', 'Japan'),
             ('KE', 'Kenya'),
             ('KG', 'Kyrgyzstan'),
             ('KH', 'Cambodia'),
             ('KI', 'Kiribati'),
             ('KM', 'Comoros'),
             ('KN', 'Saint Kitts and Nevis'),
             ('KP', "Korea, Democratic People's Republic of"),
             ('KR', 'Korea, Republic of'),
             ('KW', 'Kuwait'),
             ('KY', 'Cayman Islands'),
             ('KZ', 'Kazakhstan'),
             ('LA', "Lao People's Democratic Republic"),
             ('LB', 'Lebanon'),
             ('LC', 'Saint Lucia'),
             ('LI', 'Liechtenstein'),
             ('LK', 'Sri Lanka'),
             ('LR', 'Liberia'),
             ('LS', 'Lesotho'),
             ('LT', 'Lithuania'),
             ('LU', 'Luxembourg'),
             ('LV', 'Latvia'),
             ('LY', 'Libya'),
             ('MA', 'Morocco'),
             ('MC', 'Monaco'),
             ('MD', 'Moldova, Republic of'),
             ('ME', 'Montenegro'),
             ('MF', 'Saint Martin (French part)'),
             ('MG', 'Madagascar'),
             ('MH', 'Marshall Islands'),
             ('MK', 'Macedonia, the Former Yugoslav Republic of'),
             ('ML', 'Mali'),
             ('MM', 'Myanmar'),
             ('MN', 'Mongolia'),
             ('MO', 'Macao'),
             ('MP', 'Northern Mariana Islands'),
             ('MQ', 'Martinique'),
             ('MR', 'Mauritania'),
             ('MS', 'Montserrat'),
             ('MT', 'Malta'),
             ('MU', 'Mauritius'),
             ('MV', 'Maldives'),
             ('MW', 'Malawi'),
             ('MX', 'Mexico'),
             ('MY', 'Malaysia'),
             ('MZ', 'Mozambique'),
             ('NC', 'New Caledonia'),
             ('NE', 'Niger'),
             ('NF', 'Norfolk Island'),
             ('NG', 'Nigeria'),
             ('NI', 'Nicaragua'),
             ('NL', 'Netherlands'),
             ('NO', 'Norway'),
             ('NP', 'Nepal'),
             ('NR', 'Nauru'),
             ('NU', 'Niue'),
             ('NZ', 'New Zealand'),
             ('OM', 'Oman'),
             ('PA', 'Panama'),
             ('PE', 'Peru'),
             ('PF', 'French Polynesia'),
             ('PG', 'Papua New Guinea'),
             ('PH', 'Philippines'),
             ('PK', 'Pakistan'),
             ('PL', 'Poland'),
             ('PM', 'Saint Pierre and Miquelon'),
             ('PN', 'Pitcairn'),
             ('PR', 'Puerto Rico'),
             ('PS', 'Palestine, State of'),
             ('PT', 'Portugal'),
             ('PW', 'Palau'),
             ('PY', 'Paraguay'),
             ('QA', 'Qatar'),
             ('RE', 'Réunion'),
             ('RO', 'Romania'),
             ('RS', 'Serbia'),
             ('RU', 'Russian Federation'),
             ('RW', 'Rwanda'),
             ('SA', 'Saudi Arabia'),
             ('SB', 'Solomon Islands'),
             ('SC', 'Seychelles'),
             ('SD', 'Sudan'),
             ('SE', 'Sweden'),
             ('SG', 'Singapore'),
             ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
             ('SI', 'Slovenia'),
             ('SJ', 'Svalbard and Jan Mayen'),
             ('SK', 'Slovakia'),
             ('SL', 'Sierra Leone'),
             ('SM', 'San Marino'),
             ('SN', 'Senegal'),
             ('SO', 'Somalia'),
             ('SR', 'Suriname'),
             ('SS', 'South Sudan'),
             ('ST', 'Sao Tome and Principe'),
             ('SV', 'El Salvador'),
             ('SX', 'Sint Maarten (Dutch part)'),
             ('SY', 'Syrian Arab Republic'),
             ('SZ', 'Swaziland'),
             ('TC', 'Turks and Caicos Islands'),
             ('TD', 'Chad'),
             ('TF', 'French Southern Territories'),
             ('TG', 'Togo'),
             ('TH', 'Thailand'),
             ('TJ', 'Tajikistan'),
             ('TK', 'Tokelau'),
             ('TL', 'Timor-Leste'),
             ('TM', 'Turkmenistan'),
             ('TN', 'Tunisia'),
             ('TO', 'Tonga'),
             ('TR', 'Turkey'),
             ('TT', 'Trinidad and Tobago'),
             ('TV', 'Tuvalu'),
             ('TW', 'Taiwan, Province of China'),
             ('TZ', 'Tanzania, United Republic of'),
             ('UA', 'Ukraine'),
             ('UG', 'Uganda'),
             ('UM', 'United States Minor Outlying Islands'),
             ('US', 'United States'),
             ('UY', 'Uruguay'),
             ('UZ', 'Uzbekistan'),
             ('VA', 'Holy See (Vatican City State)'),
             ('VC', 'Saint Vincent and the Grenadines'),
             ('VE', 'Venezuela, Bolivarian Republic of'),
             ('VG', 'Virgin Islands, British'),
             ('VI', 'Virgin Islands, U.S.'),
             ('VN', 'Viet Nam'),
             ('VU', 'Vanuatu'),
             ('WF', 'Wallis and Futuna'),
             ('WS', 'Samoa'),
             ('YE', 'Yemen'),
             ('YT', 'Mayotte'),
             ('ZA', 'South Africa'),
             ('ZM', 'Zambia'),
             ('ZW', 'Zimbabwe'),
             ('nan', 'Namibia')])

In [10]:
Country_code_1 = input("Enter your value 1: ")

Enter your value 1: IN

In [11]:
Country_code_2 = input("Enter your value 2: ")

Enter your value 2: US

### Countries between IN and US

In [15]:
countries = []
for key in od.keys():
    if(key > Country_code_1) & (key < Country_code_2):
        countries.append(od[key])

In [16]:
countries.sort()

In [17]:
print(countries)

['British Indian Ocean Territory', 'Cambodia', 'Cayman Islands', 'Chad', 'Comoros', 'El Salvador', 'French Polynesia', 'French Southern Territories', 'Iceland', 'Iran, Islamic Republic of', 'Iraq', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Democratic People's Republic of", 'Korea, Republic of', 'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Macedonia, the Former Yugoslav Republic of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine, State of', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Réunion', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin (French part)', 'Saint Pierre and Miquelon', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname', 'Svalbard and Jan Mayen', 'Swaziland', 'Sweden', 'Syrian Arab Republic', 'Taiwan, Province of China', 'Tajikistan', 'Tanzania, United Republic of', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United States Minor Outlying Islands']